// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc771.TestProject2.subsystems;


import org.usfirst.frc771.TestProject2.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

import org.usfirst.frc771.TestProject2.Robot;

/**
 *
 */
public class Drive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX talonSRX1;
    private WPI_TalonSRX talonSRX2;
    private WPI_TalonSRX talonSRX3;
    private SpeedControllerGroup speedControllerGroup1;
    private WPI_TalonSRX talonSRX4;
    private WPI_TalonSRX talonSRX5;
    private WPI_TalonSRX talonSRX6;
    private SpeedControllerGroup speedControllerGroup2;
    private DifferentialDrive differentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        talonSRX1 = new WPI_TalonSRX(1);
        
        
        
        talonSRX2 = new WPI_TalonSRX(2);
        
        
        
        talonSRX3 = new WPI_TalonSRX(3);
        
        
        
        speedControllerGroup1 = new SpeedControllerGroup(talonSRX1, talonSRX2 , talonSRX3 );
        addChild("Speed Controller Group 1",speedControllerGroup1);
        
        
        talonSRX4 = new WPI_TalonSRX(4);
        
        
        
        talonSRX5 = new WPI_TalonSRX(5);
        
        
        
        talonSRX6 = new WPI_TalonSRX(6);
        
        
        
        speedControllerGroup2 = new SpeedControllerGroup(talonSRX4, talonSRX5 , talonSRX6 );
        addChild("Speed Controller Group 2",speedControllerGroup2);
        
        
        differentialDrive1 = new DifferentialDrive(speedControllerGroup1, speedControllerGroup2);
        addChild("Differential Drive 1",differentialDrive1);
        differentialDrive1.setSafetyEnabled(true);
        differentialDrive1.setExpiration(0.1);
        differentialDrive1.setMaxOutput(1.0);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    public void differentialDrive(){
        Joystick joy = Robot.oi.joystick1;
        double x = (double) joy.getRawAxis(1);
        double y = (double) joy.getRawAxis(5);
        double rate_limit = 1.5;
        differentialDrive1.tankDrive(x/rate_limit, y/rate_limit);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

